name: build
on:
  workflow_dispatch:
    inputs:
      build_app:
        description: "Build the Weather app terraform stack aswell."
        required: true
        default: false
        type: boolean
jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
    steps:
    - uses: actions/checkout@v2
    - name: Terraform_Plan
      run: make run_plan       

  terraform_apply:
    environment:
      name: approval
    needs: terraform_plan
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
    steps:
    - uses: actions/checkout@v2
    - name: Terraform_Plan
      run: make run_plan
    - name: Terraform_Apply
      run: make run_apply

  deploy_app:
    needs: terraform_apply
    runs-on: ubuntu-latest
    if: ${{ inputs.build_app }}
    steps:
    - uses: actions/checkout@v2
    - name: Initiate build in app repo
      run: >
        curl -X POST
        -H "Accept: application/vnd.github.v3+json"
        -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}"
        https://api.github.com/repos/williamchrisp/dojo-weather-app/dispatches
        -d '{"event_type":"build","client_payload":{"build":true}}'
    - name: echo build initiated for app
      run: echo "Initiated build workflow here - https://github.com/williamchrisp/dojo-weather-app"
  