name: destroy
on:
  workflow_dispatch:
    inputs:
      destroy_app:
        description: "Destroy the Weather app (Recommended - App will stop working either way!)"
        required: true
        default: true
        type: boolean
env:
  DELAY: 60
jobs:
  destroy_app:
    runs-on: ubuntu-latest
    if: ${{ inputs.destroy_app }}
    steps:
    - uses: actions/checkout@v2
    - name: Initiate build in app repo
      run: >
        curl -X POST
        -H "Accept: application/vnd.github.v3+json"
        -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}"
        https://api.github.com/repos/williamchrisp/dojo-weather-app/dispatches
        -d '{"event_type":"destroy","client_payload":{"destroy":true}}'
    - name: Delay
      run: sleep $DELAY

  terraform_destroy_plan:
    needs: destroy_app
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
    steps:
    - uses: actions/checkout@v2
    - name: Terraform_Destroy_Plan
      run: make run_destroy_plan       

  terraform_destroy_apply:
    environment:
      name: approval
    needs: terraform_destroy_plan
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
    steps:
    - uses: actions/checkout@v2
    - name: Terraform_Destroy_Apply
      run: make run_destroy_apply 