name: Destroy
on:
  push:
    branches:
      - destroy
  workflow_dispatch:
    inputs:
      destroy_app:
        description: "Destroy the Weather app terraform stack aswell."
        required: true
        default: false
        type: boolean
jobs:
  terraform_destroy_plan:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
    steps:
    - uses: actions/checkout@v2
    - name: Terraform_Destroy_Plan
      run: make run_destroy_plan       

  terraform_destroy_apply:
    environment:
      name: approval
    needs: terraform_destroy_plan
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
    steps:
    - uses: actions/checkout@v2
    - name: Terraform_Destroy_Apply
      run: make run_destroy_apply 

  destroy_app:
    runs-on: ubuntu-latest
    if: ${{ inputs.destroy_app }}
    steps:
    - name: Initiate destroy in app repo
    - run: |
        curl -X POST \
        -H "Authorization: Bearer ${{secrets.ACCESS_TOKEN}}" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/williamchrisp/dojo-weather-app/actions/workflows/destroy.yml/dispatches \
        -d '{"ref": "main"}'
    - run: echo "Initiated destroy workflow here - https://github.com/williamchrisp/dojo-weather-app"